#!/usr/bin/python3
import re
import sys
from config import config

r = re.compile(r'\$\{([^}]*)\}')

def subst(match):
    return config[match.group(1)]

for s in sys.stdin:
    print(r.sub(subst, s).rstrip('\n'))
