#!/usr/bin/python3
import sys
from config import config

f = open(sys.argv[1])
for line in f:
    if line.startswith('box_root'):
        try:
            idx = line.index('=')
            line = line[:idx] + '= ' + config['homefs_dir']
        except ValueError:
            pass
    print(line.rstrip('\n'))
